- PyEyeSim/__init__.py
> hidden markov model import optional

- PyEyeSim/__init__.py
- PyEyeSim/_comparegroups.py
comments and descriptive added
> group comparison file update

- PyEyeSim/_comparegroups.py
works for more than two groups (up to four currently) docstring update
> between group comparison update

- PyEyeSim/__init__.py
- PyEyeSim/_scanpathsim.py
scanpath similarity methods moved to seprate file _scanpathsim.py
> scanpath similarity methods

- PyEyeSim/__init__.py
- PyEyeSim/_comparegroups.py
skimage for heatmap comparison
> optional dependency

- PyEyeSim/_comparegroups.py
run RunDescriptiveFix if is has not before in group comparison (as bounds are needed)
> update group comp

- PyEyeSim/__init__.py
- PyEyeSim/_comparegroups.py
clean init.py imports from unused
clean fixdata argument, as currently only fixation data is used.. 
fixdata=1 should not be provided for EyeData initalization anymore
> cleaning init.py

- PyEyeSim/__init__.py
- PyEyeSim/_dataproc.py
- PyEyeSim/_hmm.py
- PyEyeSim/_scanpathsim.py
- PyEyeSim/_visuals.py
- PyEyeSim/scanpathsimhelper.py
hmm returns individual data for each number of clusters
saccadesel function moded to scanpathsim.py
> Saccade similarity and HMM updates

- PyEyeSim/_comparegroups.py
- PyEyeSim/_dataproc.py
- PyEyeSim/_hmm.py
- PyEyeSim/_scanpathsim.py
- PyEyeSim/_stats.py
- PyEyeSim/_visuals.py
important change: stimulus size - screen resolution difference correction performed for most analyses at the beginning, when loading images.. this many functions cleaner.
> stimulus size correction change

- PyEyeSim/__init__.py
- PyEyeSim/_comparegroups.py
- PyEyeSim/_dataproc.py
- PyEyeSim/statshelper.py
RunDescripitveFix is automatically called in DataInfo.. that is part of initalization.
gaussian filter update --> due to warning
CutAct=False by default
> multiple updates

- PyEyeSim/_comparegroups.py
- PyEyeSim/_dataproc.py
make loaded image file optional.
if no image file provided, full screen size is used as image area
> error fix in heatmaps

- PyEyeSim/_dataproc.py
fixation count edge case update.   
fixation on zero pixel are accepted
two fixations on the exact same pixel by two different participant are now counted twice
> Update fixcount calc

- .github/workflows/python-app.yml
- PyEyeSim/_dataproc.py
> Duinj patch 1

- PyEyeSim/__init__.py
- PyEyeSim/_comparegroups.py
- PyEyeSim/_visuals.py
- PyEyeSim/statshelper.py
typo in highlight grid function name
multiple comparison correction (bonferroni-holm) can handle missing values
> group comparison updates

- PyEyeSim/__init__.py
suggestion on how to adjust initialization for readability and flexibility
> warnings instead of prints, initialization pipeline in dataINfo

- PyEyeSim/__init__.py
- PyEyeSim/_comparegroups.py
- PyEyeSim/_dataproc.py
- PyEyeSim/_visuals.py
- PyEyeSim/statshelper.py
- pyproject.toml
group comparison functions are more flexible  and code cleaner
> Group comp updates

- PyEyeSim/__init__.py
- PyEyeSim/_comparegroups.py
new functions:
CompareStimGridFix
CompareStimHeatmap,
> stimulus and group heatmap comparisons separated

- PyEyeSim/_dataproc.py
param was leftover in Heatmap creation function
> fixed bug where fixCountCalc used substring param 

- PyEyeSim/_comparegroups.py
same as before for comparegroups file - value errors instead of asserts
> subsitute asserts here

- PyEyeSim/_comparegroups.py
I miswrote a variable that obviously raised an error
> misused variable

- PyEyeSim/_comparegroups.py
- PyEyeSim/_scanpathsim.py
- PyEyeSim/scanpathsimhelper.py
> scanpathcomparison updates

- PyEyeSim/_hmm.py
- PyEyeSim/_scanpathsim.py
- PyEyeSim/_visuals.py
scanpath sime all to all comparison added
> Hmm update

- PyEyeSim/__init__.py
- PyEyeSim/_hmm.py
- PyEyeSim/_scanpathsim.py
- PyEyeSim/_visuals.py
HMM all to all pipeline function added fit and CV for all stimuli, for a given num of components
> pipeline updates

- PyEyeSim/__init__.py
- PyEyeSim/_dataproc.py
- PyEyeSim/_scanpathsim.py
- PyEyeSim/_visuals.py
enabling saccade format for scanpath similarity comparisons
> possibility of comparing two pyeyesim data objects
